// ignore: depend_on_referenced_packages
import 'package:get/get.dart';

class LocalStrings extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "saad": '\nSa\'ad ',
          "EmailValidate": 'Please enter a valid email address',
          "PasswordValidation": 'Password must be at least 6',
          "PasswordOldValidation": 'Old Password must be at least 6',
          "PasswordNewValidation": "New Password must be at least 6",
          "premiumMain": "Endless conversation",
          "premiumSec1": "Subscribe now to the service",
          "premiumSec2":
              "It brings you advantages that you have never seen before.",
          "Subscription": "Subscription",
          "Subscription Now": "  Subscription Now  ",
          "dashboardHint": "Start Talking To Sa'ad...",
          "saadTyping": "Sa'ad is typing...",
          "talk": "Talk ...",
          'requestPictures': 'request pictures',
          "SaadChat": "Sa'ad - Chat",
          "Welcome": "Welcome",
          "personalInfo": "Personal Information",
          "editProfile": 'Edit Profile',
          "suggestion": ' Suggestion',
          "logout": 'Logout',
          "accountType": 'Account Type: ',
          "email": 'Email:',
          "phone": 'Phone Number',
          "name": "Name",
          "SaveChanges": 'Save Changes',
          "amazeUs": 'Amaze Us',
          "We welcome your suggestions.": "We welcome your suggestions.",
          'writeSuggestion': "Write your suggestion here",
          "sendSuggestion": 'Send Suggestion',
          "appLanguage": 'App Language:',
          "accent": 'Accent:',
          "Classical": 'Classical',
          "local": 'Local',
          "notification": 'Notification',
          "mute": 'Off',
          "on": 'On',
          "Voice options": "Voice options",
          "man": "Man",
          'Saad will do it for you in seconds':
              'Saad will do it for you in seconds',
          'Unlimited voice chats': 'Unlimited voice chats',
          "women": "Women",
          "setting": 'Setting',
          "Saad Annual Subscription Plan": "Saad Annual Subscription Plan",
          "premiumFeatures": "Premium Features",
          "voiceInteraction": "1- Voice Interaction",
          "voiceInteractionDesc1":
              "- Interact with Sa'ad using voice commands instead of text.",
          "voiceInteractionDesc2":
              "- Enjoy a natural hands-free conversation experience.",
          "imageGeneration": "2- Image Generation",
          "imageGenerationDesc1": "- Generate high-quality images.",
          "imageGenerationDesc2":
              "- Regular updates and improvements to ensure the best performance.",
          "benefits": "Benefits",
          "benefitsDesc1":
              "- Enhance user experience through voice interactions.",
          "benefitsDesc2":
              "- Creative freedom with AI-powered image generation capabilities.",
          "benefitsDesc3":
              "- Regular updates and improvements to ensure the best performance.",
          "Let's Hear Your Voice": "Let's Hear Your Voice",
          "history": "History",
          "loginEmail": "Write your email here",
          "loginPassword": "Type the password",
          "start": "start",
          "dontHaveAccoint": "Don't Have Account ? ",
          "Register": "Register",
          "Login": "Login",
          "HaveAccount": "Have Account ? ",
          "confirmPassword": "Confirm Password",
          "loginName": "Write your name",
          "nameValidation": "Name must be greater than 5",
          "phoneValidation": "Phone number must be greater than 9",
          "VaildConfirmPassword": "Passwords do not match",
          "loginError": "Error in Email or Password",
          "loginSuccess": "Login Successfully",
          "library": "Choose from library",
          "camera": "Take photo",
          "country": "Country",
          "slecetGender": "Please Select Gender",
          "slecetCountry": "Please Select Country",
          "Select a Gender": "Select a Gender",
          'Select a Country': 'Select a Country',
          'Gender': "Gender",
          'noEnternet': "No internet connection",
          'Duration': "Duration: ",
          'changePassword': "change Password",
          'Forget Password': "Forget Password",
          'No worries! Enter your old password below':
              'No worries! Enter your old password below',
          'oldPassword': 'Old Password',
          'newPassowrd': 'New Password',
          'Confirm': 'Confirm',
          'historyNewChat': 'Start Talking With Saad  ',
          "account": 'Account',
          "isDrawing": 'Wait, Saad is drawing...',
          "imgHeader": "Saad - Request a picture",
          "oldPasswordv": 'Old Passord is invalid',
          "passwordMatch": "The password and old password must be different",
          "voiceError": "I can't hear you, try saying something",
          'chooseLanguage': "Choose language"
        },
        'ar_JO': {
          "passwordMatch":
              "يجب أن تكون كلمة المرور وكلمة المرور القديمة مختلفة",
          "saad": ' سعد',
          "premiumMain": "سواليف للصبح",
          "premiumSec1": "إشترك الان في خدمة ",
          "premiumSec2": " واستمتع في مزايا وخدمات عمرك ما شفتها.",
          "Subscription": "ترقية الحساب",
          "dashboardHint": "بلش سولف مع سعد ...",
          "saadTyping": ' سعد عم يكتب ...',
          "talk": "سولف ...",
          'requestPictures': 'أطلب صور',
          "Subscription Now": "  اشترك الاَن",
          'SaadChat': '"سعد - شات"',
          "Welcome": "اهلا وسهلا",
          "personalInfo": "المعلومات الشخصية",
          "editProfile": 'تعديل الملف',
          "suggestion": ' الإقتراحات',
          "logout": 'تسجيل الخروج',
          "accountType": " نوع الحساب:",
          "email": "البريد الإلكتروني:",
          "phone": "رقم الهاتف:",
          "name": "الإسم",
          "SaveChanges": 'حفظ التغييرات',
          "amazeUs": 'إتحفنا',
          "We welcome your suggestions.": "منتشرف بإقتراحانكم",
          'writeSuggestion': "اكتب إقتراحك هون",
          "sendSuggestion": 'إرسال الإقتراح',
          "appLanguage": 'لغة التطبيق:',
          "accent": 'اللهجة:',
          "Classical": 'فصحى',
          "notification": 'الإشعارات:',
          "mute": 'صامت',
          "on": "شغال",
          "Voice options": "صوت السواليف:",
          "man": "شب",
          "local": 'عامية',
          "women": "صبية",
          "setting": 'الإعدادات',
          "Whatever the picture": "شو ما كانت الصورة",
          'Saad will do it for you in seconds': 'سعد بيعملك ياها بثواني',
          'Unlimited voice chats': ' محادثات صوتية بلا حدود',
          "Saad Annual Subscription Plan": " خطة الاشتراك السنوية في سعد",
          "premiumFeatures": "المميزات",
          "voiceInteraction": "1- ألتفاعل الصوتي",
          "voiceInteractionDesc1":
              "- التفاعل مع سعد باستخدام الأوامر الصوتية بدلاً من النصوص",
          "voiceInteractionDesc2":
              "- الاستمتاع بتجربة محادثة طبيعية وبدون استخدام اليدين.",
          "imageGeneration": "2- توليد الصور",
          "imageGenerationDesc1": "- توليد صور عالية الجودة.",
          "imageGenerationDesc2": "- تحديثات وتحسينات منتظمة لضمان أفضل أداء.",
          "benefits": "الفوائد",
          "benefitsDesc1": "- تحسين تجربة المستخدم من خلال التفاعلات الصوتية.",
          "benefitsDesc2":
              "- حرية إبداعية مع قدرات توليد الصور المدعومة بالذكاء الاصطناعي.",
          "benefitsDesc3": "- تحديثات وتحسينات منتظمة لضمان أفضل أداء.",
          "Let's Hear Your Voice": 'سمعنا صوتك',
          "history": "السجل",
          "EmailValidate": 'يرجى إدخال عنوان بريد إلكتروني صالح',
          "PasswordValidation":
              'يجب أن تكون كلمة المرور مكونة من 6 أحرف على الأقل',
          "PasswordOldValidation":
              'يجب أن تكون كلمة المرور القديمة مكونة من 6 أحرف على الأقل',
          "PasswordNewValidation":
              'يجب أن تكون كلمة المرور الجديدة مكونة من 6 أحرف على الأقل',
          "loginEmail": "اكتبلي ايميلك هون",
          "loginPassword": "اكتبلي الباسورد",
          "start": 'إبدء',
          "dontHaveAccoint": 'ليس لدي حساب ؟ ',
          "account": 'حساب',
          "Register": "سجل الان",
          "Login": "سجل الدخول",
          "HaveAccount": "لدي حساب ؟ ",
          "confirmPassword": "تاكد من الباسورد",
          "loginName": "اكتبلي اسمك هون",
          "nameValidation": "يجب أن يكون الاسم أكبر من 5",
          "phoneValidation": "يجب أن يكون الرقم أكبر من رقم 9",
          "VaildConfirmPassword": "كلمات المرور لا تتطابق",
          "oldPasswordv": 'الباسورد القديم خطآ',
          "loginError": "خطأ في البريد الإلكتروني أو كلمة المرور",
          "loginSuccess": "تم تسجيل الدخول بنجاح!",
          "library": "اختر من المكتبة",
          "camera": "التقط الصورة",
          "country": "البلد",
          "slecetGender": "الرجاء تحديد الجنس",
          "slecetCountry": "الرجاء اختيار البلد",
          "Select a Gender": "حدد الجنس",
          'Select a Country': 'اختر البلد',
          'Gender': "الجنس",
          'noEnternet': "'لا يوجد اتصال بالإنترنت",
          'Duration': "المدة: ",
          'changePassword': "تغيير كلمة المرور",
          'No worries! Enter your old password below':
              'لا تقلق! أدخل كلمة المرور القديمة أدناه',
          'Forget Password': 'نسيت كلمة المرور',
          'oldPassword': 'كلمة المرور القديمة',
          'newPassowrd': 'كلمة المرور الجديدة',
          'Confirm': 'تغيير',
          'historyNewChat': '    بلش سواليف جديده',
          "isDrawing": 'استني سعد عم يرسم ...',
          "imgHeader": 'سعد - أطلب صورة',
          "voiceError": "لا أستطيع سماعك، حاول أن تقول شيئا",
          'chooseLanguage': "اختر اللغة"
        }
      };
}
