// ignore: depend_on_referenced_packages
import 'package:get/get.dart';

class LocalStrings extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "EmailValidate": 'Please enter a valid email address',
          "PasswordValidation": 'Password must be at least 6',
          "PasswordOldValidation": 'Old Password must be at least 6',
          "PasswordNewValidation": "New Password must be at least 6",
          "logout": 'Logout',
          "email": 'Email:',
          "phone": 'Phone Number',
          "name": "Name",
          "setting": 'Setting',
          "history": "History",
          "loginEmail": "Email",
          "loginPassword": "Password",
          "start": "start",
          "dontHaveAccoint": "Don't Have Account ? ",
          "Register": "Register",
          "Login": "Login",
          "HaveAccount": "Have Account ? ",
          "confirmPassword": "Confirm Password",
          "loginName": "First Name",
          "loginSecName": "Last Name",
          "nameValidation": "Name must be greater than 5",
          "secNameValidation": "Last Name must be greater than 5",
          "phoneValidation": "Phone number must be greater than 9",
          "VaildConfirmPassword": "Passwords do not match",
          "loginError": "Error in Email or Password",
          "loginSuccess": "Login Successfully",
          "library": "Choose from library",
          "camera": "Take photo",
          "slecetGender": "Please Select Gender",
          "slecetCountry": "Please Select Country",
          "Select a Gender": "Select a Gender",
          'Gender': "Gender",
          'noEnternet': "No internet connection",
          'changePassword': "change Password",
          'Forget Password': "Forget Password",
          'No worries! Enter your old password below':
              'No worries! Enter your old password below',
          'oldPassword': 'Old Password',
          'newPassowrd': 'New Password',
          'Confirm': 'Confirm',
          "oldPasswordv": 'Old Passord is invalid',
          "passwordMatch": "The password and old password must be different",
          'searchDoctor': 'Search for doctor here',
          "founds": "founds",
        },
        'ar_JO': {
          "passwordMatch":
              "يجب أن تكون كلمة المرور وكلمة المرور القديمة مختلفة",
          "Subscription": "ترقية الحساب",
          "logout": 'تسجيل الخروج',
          "email": "البريد الإلكتروني:",
          "phone": "رقم الهاتف:",
          "name": "الإسم",
          "setting": 'الإعدادات',
          "history": "السجل",
          "EmailValidate": 'يرجى إدخال عنوان بريد إلكتروني صالح',
          "PasswordValidation":
              'يجب أن تكون كلمة المرور مكونة من 6 أحرف على الأقل',
          "PasswordOldValidation":
              'يجب أن تكون كلمة المرور القديمة مكونة من 6 أحرف على الأقل',
          "PasswordNewValidation":
              'يجب أن تكون كلمة المرور الجديدة مكونة من 6 أحرف على الأقل',
          "loginEmail": "اكتبلي ايميلك هون",
          "loginPassword": "الباسورد",
          "start": 'إبدء',
          "dontHaveAccoint": 'ليس لدي حساب ؟ ',
          "account": 'حساب',
          "Register": "سجل الان",
          "Login": "سجل الدخول",
          "HaveAccount": "لدي حساب ؟ ",
          "confirmPassword": "تاكد من الباسورد",
          "loginName": "الاسم الاول",
          "loginSecName": "الاسم الاخير",
          "nameValidation": "يجب أن يكون الاسم أكبر من 5",
          "secNameValidation": "يجب أن يكون الاسم الثاني أكبر من 5",
          "phoneValidation": "يجب أن يكون الرقم أكبر من رقم 9",
          "VaildConfirmPassword": "كلمات المرور لا تتطابق",
          "oldPasswordv": 'الباسورد القديم خطآ',
          "loginError": "خطأ في البريد الإلكتروني أو كلمة المرور",
          "loginSuccess": "تم تسجيل الدخول بنجاح!",
          "library": "اختر من المكتبة",
          "camera": "التقط الصورة",
          "slecetGender": "الرجاء تحديد الجنس",
          "Select a Gender": "حدد الجنس",
          'Gender': "الجنس",
          'noEnternet': "'لا يوجد اتصال بالإنترنت",
          'changePassword': "تغيير كلمة المرور",
          'No worries! Enter your old password below':
              'لا تقلق! أدخل كلمة المرور القديمة أدناه',
          'Forget Password': 'نسيت كلمة المرور',
          'oldPassword': 'كلمة المرور القديمة',
          'newPassowrd': 'كلمة المرور الجديدة',
          'Confirm': 'تغيير',
          'chooseLanguage': "اختر اللغة",
          'searchDoctor': 'ابحث عن طبيب هنا',
          "founds": "نتيجة"
        }
      };
}
