// ignore: depend_on_referenced_packages
import 'package:get/get.dart';

class LocalStrings extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'founds': " founds",
          'errorDoctor': "Currently, there are no Doctor available for you",
          'Reviews': 'Reviews',
          'Centers': 'Centers',
          'Freelancer': 'Freelancer',
          'On ': 'On ',
          ' at ': ' at ',
          "Write a review message:": "Write a review message",
          'Submit': 'Submit',
          'later': 'Later',
          'Yes': 'Yes',
          'No': 'No',
          "let us know the reason below": "let us know the reason below",
          "Enter you message here": "Enter your message here",
          "Attended": 'Attended',
          "Details": 'Details',
          "patients": 'patients',
          "rating": 'rating',
          "About Me": "About ",
          " see less": " see less",
          " see more": " see more",
          "Working Time": "Working Time",
          "Services": "Services",
          'There is no services for this vendor':
              'There is no services for this doctor',
          'Error': "Error",
          "Select Service before Continue": "Select Service before Continue",
          "Book Appointment": "Book Appointment",
          "All Reviews": "All Reviews",
          "Booking Appointment": "Booking Appointment",
          "Select Date": "Select Date",
          "Select Hour": "Select Hour",
          "noTime": "There is no available\n time this day",
          'Please Select a Day': 'Please Select a Day',
          'Please Select a Hour': 'Please Select a Hour',
          'All': 'All',
          "Don't see you Preference": "Don't see you Preference",
          "Join the Wishing List": "Join the Wishing List",
          'Congratulations': 'Congratulations',
          "Done": "Done",
          "Range Date": "Date Range",
          "Time Date": "Time Range",
          "Waiting list": "Waiting list",
          "Currently, there are no History available for you":
              "Currently, there are no History available for you",
          "Enter your basic information to create your account":
              "Enter your basic information to create your account",
          ////////////////
          "EmailValidate": 'Please enter a valid email address',
          "PasswordValidation": 'Password must be at least 6',
          "PasswordOldValidation": 'Old Password must be at least 6',
          "PasswordNewValidation": "New Password must be at least 6",
          "logout": 'Logout',
          "email": 'Email:',
          "phone": 'Phone Number',
          "name": "Name",
          "setting": 'Setting',
          "history": "History",
          "loginEmail": "Email",
          "loginPassword": "Password",
          "start": "start",
          "dontHaveAccoint": "Don't Have Account ? ",
          "Register": "Register",
          "Login": "Login",
          "HaveAccount": "Have Account ? ",
          "confirmPassword": "Confirm Password",
          "loginName": "Name",
          "loginSecName": "Last Name",
          "nameValidation": "Name must be greater than 5",
          "secNameValidation": "Last Name must be greater than 5",
          "phoneValidation": "Phone number must be greater than 9",
          "VaildConfirmPassword": "Passwords do not match",
          "loginError": "Error in Phone number or Password",
          "loginSuccess": "Login Successfully",
          "library": "Choose from library",
          "camera": "Take photo",
          "slecetGender": "Please Select Gender",
          "slecetCountry": "Please Select Country",
          "Select a Gender": "Select a Gender",
          'Gender': "Gender",
          'noEnternet': "No internet connection",
          'changePassword': "change Password",
          'Forget Password': "Forget Password",
          'No worries! Enter your old password below':
              'No worries! Enter your old password below',
          'oldPassword': 'Old Password',
          'newPassowrd': 'New Password',
          'Confirm': 'Confirm',
          "oldPasswordv": 'Old Passord is invalid',
          "passwordMatch": "The password and old password must be different",
          'searchDoctor': 'Search here',
          "From": "From ",
          'To': "To ",
          'To1': " To ",
          'Message': 'Message',

          "Join Waiting list": "Join Waiting list",
          "Please select both start and end dates.":
              "Please select both start and end dates.",
          "Please enter both start and end times.":
              "Please enter both start and end times.",
          "Start time cannot be greater than end time.":
              "Start time cannot be greater than end time.",
          "Notice": "Notice",
          "The doctor does not work on some selected day":
              "The doctor does not work on some selected day",
          "My Bookings": "My Bookings",
          'Pending': 'Pending', 'Upcoming': 'Upcoming',
          'DoneBooking': 'Done',
          "There Is No Available booking": "There Is No Available booking",
          'Create Profile': 'Create Profile ',
          "Profile Details": "Profile Details",
          '5 min': '5 min',
          'To continue building your profile, start Questionnaire.':
              'To continue building your profile, start Questionnaire.',
          "Currently, there are no bookings available for you":
              "Currently, there are no\n bookings available for you",
          'Age': 'Age: ',
          "Today Booking": "Today Booking",
          "there is no booking for today": "there is no booking for today",
          "Upcoming Booking": "Upcoming Booking",
          "Today": "Today",
          "Waiting": "Waiting",
          'Do you want to remove the time from the schedule':
              'Do you want to remove the time from the schedule',
          "Absent": 'Absent',
          'Reject': 'Reject',
          "Accept": "Accept",
          'My Services': 'My Services',
          "Add services +": "Add services +",
          "Currently, there are no Services add for you":
              "Currently, there are no Services add for you",
          "Edit": 'Edit',
          'Delete': 'Delete',
          "Add service": "Add service",
          "Service Name": "Service Name",
          "pick image that will represend the service you will provide":
              "pick image that will represend the service you will provide",
          'Description': 'Description',
          "Price": "Price",
          "Add": 'Add',
          "Make sure all fields are filed": "Make sure all fields are filled",
          "Would you like to add any post-care instructions":
              "Would you like to add any post-care instructions ",
          "Service Post instruction": "Service Post instruction",
          "How many days should these post-care instructions be followed?":
              "How many days should these post-care instructions be followed?",
          "Please enter a valid number": "Please enter a valid number",
          "Days": "Days",
          "Please list any specific aftercare guidelines, such as things the patient should avoid or steps to follow during this period.":
              "Please list any specific aftercare guidelines, such as things the patient should avoid or steps to follow during this period.",
          "Day": "Day ",
          "Post Instructions": "Post Instructions",
          "Add Instruction": "Add Instruction",
          'Pationt Details': 'Patient Details',
          'Update': 'Update',
          "Hi, Welcome Back!": "Hi, Welcome Back!",
          "Hope you’re doing fine.": "Hope you’re doing fine.",
          "Forgot password?": "Forgot password?",
          "Enter your Email, we will send you a verification code.":
              "Enter your Email, we will send you a verification code.",
          "send": "Send",
          "Email does not exist.": "Email does not exist.",
          'Verification Code is not Correct':
              'Verification Code is not Correct',
          "Password changed successfully \n try login now":
              "Password changed successfully \n try login now",
          "Please cheack you email": "Please check you email",
          "OTP Verification": "OTP Verification",
          "Enter the verification code we just sent on your Email":
              "Enter the verification code we just sent on your Email",
          "Continue": "Continue",
          "Resend OTP in": "Resend OTP in",
          "Resend": "Resend",
          'Something went wrong.': 'Something went wrong.',
          "Register as:": "Register as:",
          "User": 'User',
          'Clinic': 'Clinic',
          "Profile Image": "Profile Image",
          "Specialty": "Specialty",
          'Select a Specialty': 'Select a Specialty',
          "Address": "Address",
          "Business License": "Business License",
          "Create Account": "Create Account",
          "We are here to help you!": "We are here to help you!",
          "next": 'Next',
          "Date of Birth": "Date of Birth",
          "Your appointment is Add to the Waiting list":
              "Your appointment is Add to the Waiting list",
          "Select Language": "Select Language",
          "Choose a language for your Application.":
              "Choose a language for your Application.",
          "English": 'English',
          'Please Select a Date of Birth': 'Please Select a Date of Birth',
          "Arabic": 'Arabic',
          "Resend OTP in ": 'Resend OTP in ',
          'seconds': 'seconds ',
          "Email already exists": 'Email already exists',
          "Are you sure you want to delete this reservation?":
              "Are you sure you want to delete this reservation?",
          "Cancel": "Cancel",
          "Reschedule": "Reschedule",
          "waitingVendor":
              "Thank you! Please wait while we review your application.",
          "Select working Hours": "Select working Hours",

          "FouthPageHeader":
              "Select the days and hours you're available for patient consultations or clinic services",
          "Select working days": "Select working days",
          "Please select at least one working day.":
              "Please select at least one working day.",
          "Please select both opening and closing hours.":
              "Please select both opening and closing hours.",
          "Opening hours must be earlier than closing hours.":
              "Opening hours must be earlier than closing hours.",
          "It will take a few second": "It will take a few second",
          "post-care instructions": "post-care instructions",
          "Advice": "Advice",
        },
        'ar_JO': {
          "Advice": "نصيحة",

          "post-care instructions": "تعليمات ما بعد الرعاية",
          "It will take a few second": "سوف يستغرق الأمر بضع ثوان",
          "Opening hours must be earlier than closing hours.":
              "يجب أن تكون ساعات العمل قبل ساعات الإغلاق.",
          "Please select both opening and closing hours.":
              "الرجاء تحديد ساعات الافتتاح والإغلاق.",
          "Please select at least one working day.":
              "الرجاء تحديد يوم عمل واحد على الأقل.",
          "Select working days": "حدد أيام العمل",
          "Select working Hours": "اختر ساعات العمل",
          "waitingVendor": "شكرًا لك! يرجى الانتظار بينما نقوم بمراجعة طلبك.",
          'Cancel': "الغاء",
          'Email already exists': 'البريد الإلكتروني موجود بالفعل',
          "Reschedule": "إعادة الجدولة",
          'seconds': 'ثواني ',
          "Are you sure you want to delete this reservation?":
              "هل أنت متأكد أنك تريد حذف هذا الحجز؟",
          'Resend OTP in ': 'إعادة إرسال OTP في',
          'Arabic': 'عربي',
          'English': 'إنجليزي',
          "Choose a language for your Application.": "اختر لغة لتطبيقك.",
          "Select Language": "اختر اللغة",
          "Your appointment is Add to the Waiting list":
              "موعدك تم إضافته إلى قائمة الانتظار",
          "Date of Birth": "تاريخ الميلاد",
          "next": 'التالي',
          "FouthPageHeader":
              "حدد الأيام والساعات المتاحة لك لاستشارة المرضى أو خدمات العيادة",
          "We are here to help you!": "نحن هنا لمساعدتك!",
          "Create Account": "إنشاء حساب",
          "Enter your basic information to create your account":
              "أدخل معلوماتك الأساسية لإنشاء حسابك",
          "Address": "عنوان",
          "Business License": "رخصة تجارية",
          'Select a Specialty': "اختر التخصص",
          "Specialty": "التخصص",
          "Profile Image": 'صورة الملف الشخصي',
          'Clinic': 'عيادة',
          'User': "مستخدم",
          "Register as:": 'التسجيل ك',
          'Something went wrong.': "لقد حدث خطأ ما.",
          "OTP Verification": "التحقق من الرمز",
          "Enter the verification code we just sent on your Email":
              "أدخل رمز التحقق الذي أرسلناه إلى بريدك الإلكتروني",
          "Continue": "استمر",
          "Resend OTP in": "إعادة إرسال الرمز خلال",
          "Resend": "إعادة إرسال",
          "Please cheack you email": "يرجى التحقق من بريدك الإلكتروني",
          "Password changed successfully \n try login now":
              "تم تغيير كلمة المرور بنجاح \n حاول تسجيل الدخول الآن",
          'Verification Code is not Correct': "رمز التحقق غير صحيح",
          "Email does not exist.": "البريد الإلكتروني غير موجود.",
          "send": "إرسال",
          "Enter your Email, we will send you a verification code.":
              "أدخل بريدك الإلكتروني، وسوف نرسل لك رمز التحقق.",
          "Forgot password?": "هل نسيت كلمة السر؟",
          "Hope you’re doing fine.": "أتمنى أن تكون بخير.",
          "Hi, Welcome Back!": "مرحبا بك مرة أخرى!",
          "Currently, there are no History available for you":
              "حاليًا، لا يوجد تاريخ متاح لك",
          "Waiting list": "قائمة الانتظار",

          'Update': 'تحديث',
          'Pationt Details': "تفاصيل المريض",
          "Profile Details": "تفاصيل الملف الشخصي",
          "Add Instruction": "إضافة التعليمات",
          "Post Instructions": " التعليمات",
          "Day": "يوم ",
          "Please list any specific aftercare guidelines, such as things the patient should avoid or steps to follow during this period.":
              "يرجى إدراج أي إرشادات محددة للعناية اللاحقة، مثل الأشياء التي يجب على المريض تجنبها أو الخطوات التي يجب اتباعها خلال هذه الفترة.",
          'Days': 'أيام',
          "Please enter a valid number": "الرجاء إدخال رقم صالح",
          "How many days should these post-care instructions be followed?":
              "كم يوما يجب اتباع تعليمات الرعاية اللاحقة؟",
          "Service Post instruction": "تعليمات الخدمة",
          "Would you like to add any post-care instructions":
              "هل ترغب في إضافة أي تعليمات للعناية اللاحقة",

          "Add": 'إضافة',

          "Make sure all fields are filed": "تأكد من ملء كافة الحقول",
          "Price": "سعر",
          'Description': "وصف",
          "Service Name": "اسم الخدمة",
          "pick image that will represend the service you will provide":
              "اختر الصورة التي تمثل الخدمة التي ستقدمها",
          "Add service": "إضافة خدمة",
          'Delete': 'مسح',
          'Edit': 'تعديل',
          "Currently, there are no Services add for you":
              "حاليًا، لا توجد خدمات متاحة لك",
          'My Services': 'خدماتي',
          "Add services +": "إضافة خدمات +",
          'Accept': 'قبول',
          'Reject': 'رفض',
          'Absent': 'غائب',
          'Do you want to remove the time from the schedule':
              'هل تريد إزالة الوقت من الجدول الزمني؟',
          "Waiting": "منتظر",
          "Today": "اليوم",
          "Upcoming Booking": "الحجز القادم",
          "Today Booking": "الحجز اليوم",
          "there is no booking for today": "لا يوجد حجز لهذا اليوم",
          "Currently, there are no bookings available for you":
              "حاليًا، لا توجد حجوزات متاحة لك",
          'Age': 'عمر: ',
          'To continue building your profile, start Questionnaire.':
              'لمواصلة بناء ملفك الشخصي، ابدأ الاستبيان.',
          "There Is No Available booking": "لا يوجد حجز متاح",
          'Create Profile': 'إنشاء الملف الشخصي ',
          '5 min': '5 دقائق',
          'DoneBooking': 'انتهى',
          'Pending': 'قيد الانتظار',
          'Upcoming': 'قادم',
          "My Bookings": "حجوزاتي",
          "The doctor does not work on some selected day":
              "الطبيب لا يعمل في يوم محدد",
          "Notice": "ملحوظة",
          "Start time cannot be greater than end time.":
              "لا يمكن أن يكون وقت البدء أكبر من وقت النهاية.",
          "Please enter both start and end times.":
              "الرجاء إدخال وقت البداية والنهاية.",
          "Please select both start and end dates.":
              "الرجاء تحديد تاريخي البداية والنهاية.",
          "Join Waiting list": "الانضمام إلى قائمة الانتظار",
          'Message': 'رسالة',
          "Range Date": 'نطاق التاريخ',
          "Time Date": 'نطاق الوقت',
          "founds": "نتيجة",
          'errorDoctor': "حاليا، لا يوجد طبيب متاح لك",
          'Centers': 'المراكز',
          "Write a review message:": "اكتب رسالة مراجعة",
          'Submit': 'إرسال',
          'Freelancer': 'عامل مستقل',
          'On ': 'يوم ',
          ' at ': ' على ',
          'later': 'لاحقًا',
          'Yes': 'نعم',
          'No': 'لا',
          "let us know the reason below": "أخبرنا السبب أدناه",
          "Enter you message here": "أدخل رسالتك هنا",
          "Attended": 'حضر',
          "Details": 'تفاصيل',
          "patients": 'المرضى',
          "rating": 'تصنيف',
          "About Me": "نبذة عن ",
          " see less": " أقل",
          " see more": " المزيد",
          "Working Time": "وقت العمل",
          "Services": "الخدمات",
          'There is no services for this vendor': "لا توجد خدمات لهذا الطبيب",
          'Error': "خطأ",
          "Select Service before Continue": "حدد الخدمة قبل المتابعة",
          "Book Appointment": "حجز موعد",
          "All Reviews": "كل المراجعات",
          "Booking Appointment": "حجز موعد",
          "Select Date": "اختر التاريخ",
          "Select Hour": "اختر الساعة",
          "noTime": "لا يوجد وقت متاح\n هذا اليوم",
          'Please Select a Day': "الرجاء اختيار اليوم",
          'Please Select a Date of Birth': "الرجاء تحديد تاريخ الميلاد",
          'Please Select a Hour': "الرجاء تحديد ساعة",
          'All': 'الكل',
          "Don't see you Preference": 'لم تجد الموعد المناسب؟',
          "Join the Wishing List": "انضم إلى قائمة الرغبات",
          "Congratulations": 'تهانينا',
          "Done": "تم",
          "From": "من ",
          'To': "إلى",

          'To1': " إلى ",
          /////////////
          "passwordMatch":
              "يجب أن تكون كلمة المرور وكلمة المرور القديمة مختلفة",
          "Subscription": "ترقية الحساب",
          "logout": 'تسجيل الخروج',
          "email": "البريد الإلكتروني:",
          "phone": "رقم الهاتف",
          "name": "الإسم",
          "setting": 'الإعدادات',
          "history": "السجل",
          "EmailValidate": 'يرجى إدخال عنوان بريد إلكتروني صالح',
          "PasswordValidation":
              'يجب أن تكون كلمة المرور مكونة من 6 أحرف على الأقل',
          "PasswordOldValidation":
              'يجب أن تكون كلمة المرور القديمة مكونة من 6 أحرف على الأقل',
          "PasswordNewValidation":
              'يجب أن تكون كلمة المرور الجديدة مكونة من 6 أحرف على الأقل',
          "loginEmail": "بريد إلكتروني",
          "loginPassword": "الباسورد",
          "start": 'إبدء',
          "dontHaveAccoint": 'ليس لدي حساب ؟ ',
          "account": 'حساب',
          "Register": "سجل الان",
          "Login": "سجل الدخول",
          "HaveAccount": "لدي حساب ؟ ",
          "confirmPassword": "تاكد من الباسورد",
          "loginName": "الاسم ",
          "loginSecName": "الاسم الاخير",
          "nameValidation": "يجب أن يكون الاسم أكبر من 5",
          "secNameValidation": "يجب أن يكون الاسم الثاني أكبر من 5",
          "phoneValidation": "يجب أن يكون الرقم أكبر من رقم 9",
          "VaildConfirmPassword": "كلمات المرور لا تتطابق",
          "oldPasswordv": 'الباسورد القديم خطآ',
          "loginError": "خطأ في رقم الهاتف أو كلمة المرور",
          "loginSuccess": "تم تسجيل الدخول بنجاح!",
          "library": "اختر من المكتبة",
          "camera": "التقط الصورة",
          "slecetGender": "الرجاء تحديد الجنس",
          "Select a Gender": "حدد الجنس",
          'Gender': "الجنس",
          'noEnternet': "'لا يوجد اتصال بالإنترنت",
          'changePassword': "تغيير كلمة المرور",
          'No worries! Enter your old password below':
              'لا تقلق! أدخل كلمة المرور القديمة أدناه',
          'Forget Password': 'نسيت كلمة المرور',
          'oldPassword': 'كلمة المرور القديمة',
          'newPassowrd': 'كلمة المرور الجديدة',
          'Confirm': 'تأكيد',
          'chooseLanguage': "اختر اللغة",
          'searchDoctor': 'ابحث هنا',
          'Reviews': 'تقييمات',
        }
      };
}
