// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKhFFkdjysPSyYVHflsleSEY8cKb_yR_0',
    appId: '1:269801959308:web:fa175fff544d1fdc1db0a9',
    messagingSenderId: '269801959308',
    projectId: 'gens-3bb19',
    authDomain: 'gens-3bb19.firebaseapp.com',
    storageBucket: 'gens-3bb19.appspot.com',
    measurementId: 'G-MBWFC8E3KW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdLJwJ1phBZmBtsyViV6KPCuM6DWYjXcY',
    appId: '1:269801959308:android:a6e12afa98e8d7a41db0a9',
    messagingSenderId: '269801959308',
    projectId: 'gens-3bb19',
    storageBucket: 'gens-3bb19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZwH_kfhOfnM8unezTRfkTf17z4_Fkd1s',
    appId: '1:269801959308:ios:04050447391f6e2c1db0a9',
    messagingSenderId: '269801959308',
    projectId: 'gens-3bb19',
    storageBucket: 'gens-3bb19.appspot.com',
    iosBundleId: 'com.generation.genSkin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZwH_kfhOfnM8unezTRfkTf17z4_Fkd1s',
    appId: '1:269801959308:ios:f2269078877612ea1db0a9',
    messagingSenderId: '269801959308',
    projectId: 'gens-3bb19',
    storageBucket: 'gens-3bb19.appspot.com',
    iosBundleId: 'com.example.gens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKhFFkdjysPSyYVHflsleSEY8cKb_yR_0',
    appId: '1:269801959308:web:c920bf4eec491f1e1db0a9',
    messagingSenderId: '269801959308',
    projectId: 'gens-3bb19',
    authDomain: 'gens-3bb19.firebaseapp.com',
    storageBucket: 'gens-3bb19.appspot.com',
    measurementId: 'G-DCDDLHC7MP',
  );

}